# Generated by Django 5.2.4 on 2025-07-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('flavour', models.CharField(choices=[('spicy', 'Spicy'), ('non-spicy', 'Non-Spicy')], max_length=20)),
            ],
            options={
                'unique_together': {('name', 'flavour')},
            },
        ),
    ]
